# Generated by Django 5.0.2 on 2024-02-26 05:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('reason', models.CharField(choices=[('birthday', 'День рождения'), ('wedding', 'Свадьба'), ('treatment', 'Лечение')], max_length=255)),
                ('description', models.TextField()),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('collected_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('contributors_count', models.IntegerField(default=0)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='collect_covers/')),
                ('end_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('collect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='donation_app.collect')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('date', models.DateTimeField()),
                ('collect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation_app.collect')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation_app.payment')),
            ],
        ),
        migrations.AddField(
            model_name='collect',
            name='donations',
            field=models.ManyToManyField(related_name='collects', through='donation_app.Donation', to='donation_app.payment'),
        ),
    ]
