version: '3.12'

services:
  web:
    build: .
    command: python manage.py runserver  0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A dcs worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis